

export RISCV_GCC=/data/mirror/riscv
export RISCV_ARCH=riscv32-unknown-elf

#export RISCV=$(RISCV_GCC)/$(RISCV_ARCH)
export RISCV=$(RISCV_GCC)

<<<<<<< HEAD
export LLVM=/data/mirror/llvm/build-release
=======
export LLVM=/data2/home/cese4040-10/Desktop/compiler/llvm/build-release
>>>>>>> c604b1b (Initial commit with Path B xaes32esmi LLVM builtin)

CC      = $(RISCV)/bin/$(RISCV_ARCH)-gcc
AR      = $(RISCV)/bin/$(RISCV_ARCH)-ar
OBJDUMP = $(RISCV)/bin/$(RISCV_ARCH)-objdump
SIZE    = $(RISCV)/bin/$(RISCV_ARCH)-size
OBJCOPY = $(RISCV)/bin/$(RISCV_ARCH)-objcopy
#PK      = $(RISCV)/riscv32-unknown-elf/bin/pk
LD      = $(RISCV)/bin/$(RISCV_ARCH)-ld

LLVMCC  = $(LLVM)/bin/clang

XLEN            = 32

<<<<<<< HEAD
CONF_ARCH       = rv32imac_zicsr
=======
CONF_ARCH       = rv32imac_zicsr_xaes32esmi
>>>>>>> c604b1b (Initial commit with Path B xaes32esmi LLVM builtin)

CONF_ABI        = ilp32

CONF_CFLAGS     = -Os -march=$(CONF_ARCH) -mabi=$(CONF_ABI)

